# default config
project_name = 'coy'
port = 5001

repo = 'eblahm/coy'
repo_url = 'https://github.com/eblahm/coy'
content_root = 'src/server/content'

session_secret = '(((((((((( 0-0~ ))))))))))'

[github]
  client_id = '3a76a08e13f238323cf1'
  client_secret = 'f10633beddeb5c2512d852260af60f29ecb2f38a'
  redirect_uri = 'http://127.0.0.1:5001/github/callback'
  scope = 'repo,user'

[redis]
  port = 6379
  url = '127.0.0.1'

