# default config
project_name = 'coy'
port = 5001
ssl = true

repo = 'eblahm/coy'
repo_url = 'https://github.com/eblahm/coy'
content_root = 'src/server/content'
session_secret = '(((((((((( 0-0~ ))))))))))'

google_analytics_id='UA-12345678-1'

[github]
  api_url = 'https://api.github.com'
  client_id = '~~id here~~'
  client_secret = '~~~ secret here ~~~'
  redirect_uri = 'http://127.0.0.1:5001/github/callback'
  scope = 'repo,user'

[redis]
  port = 6379
  url = '127.0.0.1'

[blog]
  [blog.categories]
    # key = 'description'
    # add as many as you like
    fragments = '...Just thoughts that come to mind, not fully formed enough to be blog posts.  Or maybe just a quote or picture or some other media...'
    articles = '...longer form stuff...'
    other = '...other stuff...'
  [blog.rss]
    included_categories=['fragments', 'articles']
    title='the works of Matthew Halbe'
    description="""
the title pretty much sums it up.  you'd be bored if I summed
it up using several comma separtated 6-12 letter words. So, Ill just let
you imagine the subject matter enstead"""
    managingEditor='Matthew Halbe'
    language='en'
    image_url='http://www.gravatar.com/avatar/6af8e2870fd7c4a74b8692f0c997522e'


